/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_daos_obj_DaosObjClient_DataTypesSizes */

#ifndef _Included_io_daos_obj_DaosObjClient_DataTypesSizes
#define _Included_io_daos_obj_DaosObjClient_DataTypesSizes
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
